# Generated by Django 3.0.7 on 2020-07-05 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmoneytracker', '0005_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
