version: '3'

services:
  db:
    container_name: postgresdb
    image: postgres
    env_file:
      - .env
    

  web:
    container_name: django
    build: 
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/code
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db

